infinilabs/coco-app

- .vscode/settings.json
- pnpm-lock.yaml
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/autostart.rs
- src-tauri/src/lib.rs
- On windows, open settings method :
```js
import { listen } from '@tauri-apps/api/event';
listen('open_settings',()=>{
// open settings window by tauri api
})
```
- Change autostart
```js
invoke("change_autostart", {open:true}) //open
invoke("change_autostart", {open:false}) // close
```
> Adapt to Windows

- .env
- .vscode/settings.json
- package.json
- pnpm-lock.yaml
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/capabilities/default.json
- src-tauri/src/lib.rs
- src/api/request.ts
- src/api/tauriFetchClient.ts
- src/components/ChatAI/Chat.tsx
- src/components/ChatAI/index.tsx
- src/hooks/useEscape.ts
- src/utils/env.ts
- src/vite-env.d.ts
- vite.config.ts
This pull request includes multiple changes to support environment configuration, dependency updates, and code cleanup. The most important changes include adding environment variables, updating dependencies, and removing unused code related to the `tauri-nspanel` plugin.
* Added `COCO_SERVER_URL` and `COCO_WEBSOCKET_URL` to the `.env` file for server and websocket URLs.
* Introduced `clientEnv` in `src/utils/env.ts` to manage environment variables in the client code.
* Updated `vite.config.ts` to use environment variables from `.env` for proxy configuration. [[1]](diffhunk://#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890ddR4-R9) [[2]](diffhunk://#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890ddL37-R46)
* Added `dotenv` dependency in …
> fix: Esc key failure issue & removing unused code related to the tauri-nspanel plugin & introduct the server variable name

- src-tauri/src/common/document.rs
- src-tauri/src/common/mod.rs
- src-tauri/src/common/search_response.rs
- src-tauri/src/server/connector.rs
- src-tauri/src/server/search.rs
- src/components/Search/DocumentList.tsx
- src/components/Search/DropdownList.tsx
- src/components/Search/Search.tsx
This pull request introduces several changes to the `src-tauri` and `src/components` directories, primarily focusing on the addition of new data structures, refactoring of existing functions, and updates to the front-end components to handle the new data structures.
* **New Data Structures**:
- Added new structs such as `RichLabel`, `DataSourceReference`, `UserInfo`, `EditorInfo`, and `Document` in `src-tauri/src/common/document.rs` to represent various entities.
- Introduced `QuerySource`, `QueryHits`, and `FailedRequest` structs in `src-tauri/src/server/search.rs` to structure the search response more effectively. [[1]](diffhunk://#diff-741dbb2ea9636cda91f990a26e4fa320f45861daeed7c0cfa6083a1465dfcbe9R2) [[2]](diffhunk://#diff-741dbb2ea9636cda91f990a26e4fa320f45861daeed7c0cfa6083a1465dfcb …
> refactor: refactoring search response

- src-tauri/src/server/search.rs
This pull request includes changes to the `query_coco_servers` function in `src-tauri/src/server/search.rs` to improve error handling and logging. The most important changes are:
Error handling and logging improvements:
* Added a check to verify if the status code indicates a successful request (2xx) before parsing the response.
* Enhanced logging by adding failed requests to the `failed_requests` list when the status code is not successful.
* Improved readability and maintainability by formatting the code to handle errors and log failures more clearly.
> refactor: refactoring to check status code before parse the response

- src/main.css
This pull request includes a small change to the `src/main.css` file. The change adds a new primary color variable for the dark theme.
* [`src/main.css`](diffhunk://#diff-e161de5730429dfd420b12db03e6cf956bede92a68ada7ed8a33b268fcf3c95aR42): Added `--coco-primary-color` variable with the value `rgb(149, 5, 153)` to the dark theme.
> fix: missing color for dark theme

- src-tauri/Cargo.toml
- src-tauri/src/lib.rs
- src-tauri/src/setup/mod.rs
This pull request includes several changes to the `src-tauri` project, focusing on conditional compilation for macOS, code refactoring, and dependency management. The most important changes are listed below:
* Added conditional compilation for the `tauri-nspanel` plugin in `Cargo.toml` and `src/lib.rs` to ensure it is only included when targeting macOS. [[1]](diffhunk://#diff-fe4c6a80a21e81339e2e0faeb9134d0f9636c168987df13c8abf1927a1caee39R56-R58) [[2]](diffhunk://#diff-eabcebd0ae5c9b77a5247e1bdbdb88b1869fc0c932d0ef0cf2ecf9ee5221be7cR68-R75)
* Refactored the `run` function in `src/lib.rs` to use `app_builder` for plugin initialization, improving readability and maintainability.
* Updated the `init` function in `src/lib.rs` to explicitly type the `registry` variable, enhancing code …
> chore: fix build for linux

- docs/.gitignore
- docs/content.en/_index.md
- docs/content.en/docs/_index.md
- docs/content.en/docs/getting-started/installation/screenshot.md
- docs/content.en/docs/getting-started/screenshot.md
> fix: docs image link

- src/utils/platform.ts
> feat: add methods to detect the Windows and Linux platforms

- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatMessage.tsx
- src/components/Assistant/SourceResult.tsx
- src/components/Search/SearchListItem.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/pages/chat/index.tsx
> fix: some bugs in chat

- .github/workflows/release.yml
- .release-it.ts
- package.json
- pnpm-lock.yaml
- scripts/release.ts
- src-tauri/tauri.conf.json
> chore: support for github action releases

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/lib.rs
> chore: improve app startup, init application search in background

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/server/auth.rs
- src-tauri/src/server/connector.rs
- src-tauri/src/server/http_client.rs
- src-tauri/src/server/websocket.rs
- src-tauri/src/shortcut.rs
- src/components/Cloud/Cloud.tsx
> refactor: refactoring login

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/search/mod.rs
> feat: add timeout to fusion search

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/lib.rs
- src-tauri/src/local/application.rs
- src-tauri/src/server/datasource.rs
- src-tauri/src/server/http_client.rs
> chore: init icons in background during start

- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatHeader.tsx
- src/components/Footer.tsx
> fix: scroll & chat switch

- src-tauri/src/setup/mac.rs
support for listening to macos ns_panel window move and resize events
> feat: support for listening to macos ns_panel window move and resize events

- src/components/Search/Footer.tsx
- src/components/Search/Search.tsx
- src/main.tsx
- src/utils/keyboardUtils.ts
- src/utils/platform.ts
update the way get the platform
> refactor: update the way get the platform

- src/pages/main/index.tsx
> feat: windows uses the default window angle

- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatHeader.tsx
- src/pages/chat/index.tsx
> chore: history component

- src/components/Cloud/Cloud.tsx
- src/components/Settings/SettingsToggle.tsx
disable service switch color changed to red
> refactor: disable service switch color changed to red

- src/components/Cloud/Cloud.tsx
fix the problem of incorrect display of toggle service enable state
> fix: the problem of incorrect display of toggle service enable state

- src/components/Common/Transition.tsx
- src/components/Search/Search.tsx
- src/pages/main/index.tsx
fix white space at the bottom of chat
> fix: white space at the bottom of chat

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/assistant/mod.rs
- src-tauri/src/common/assistant.rs
- src-tauri/src/common/http.rs
- src-tauri/src/common/mod.rs
- src-tauri/src/lib.rs
- src-tauri/src/server/auth.rs
- src-tauri/src/server/connector.rs
- src-tauri/src/server/datasource.rs
- src-tauri/src/server/http_client.rs
- src-tauri/src/server/profile.rs
- src-tauri/src/server/servers.rs
> refacotr: refactoring assistant api

- src-tauri/src/common/health.rs
- src-tauri/src/server/datasource.rs
- src-tauri/src/server/servers.rs
> refactor: refactoring refresh server's info api

- src-tauri/src/lib.rs
> feat: remember the position of the main window on the same monitor

- src-tauri/src/assistant/mod.rs
- src-tauri/src/common/assistant.rs
> fix: add missing message parameter to chat send api

- src/main.css
Fixed the problem shown in the video
https://github.com/user-attachments/assets/78821810-9fac-431f-8fed-a4f6bf6b217f
> fix: fixed bouncing when scrolling to the top and bottom of macOS pages

- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatHeader.tsx
- src/components/Assistant/Sidebar.tsx
- src/pages/chat/index.tsx
> fix: chat switch

- tailwind.config.js
counting safelist in tailwindcss configuration
> chore: counting safelist in tailwindcss configuration

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/assistant/mod.rs
- src-tauri/src/common/datasource.rs
- src/components/Assistant/Chat.tsx
> refactor: remove websocket_session_id from message request

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatHeader.tsx
- src/components/Assistant/ChatMessage.tsx
- src/components/Assistant/SourceResult.tsx
- src/components/Cloud/Cloud.tsx
- src/components/Settings/GeneralSettings.tsx
- src/hooks/useShortcutEditor.ts
- src/utils/index.ts
Refactor: the display of search results and the logic of creating new chats
> fix: source dispaly & new chat

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/assistant/mod.rs
- src/components/Assistant/Chat.tsx
- src/components/Search/InputBox.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/stores/searchStore.ts
networked search supports selection of data sources
> feat: networked search supports selection of data sources

- src/main.css
- src/pages/main/index.tsx
optimized the effect of selecting text
> refactor: optimized the effect of selecting text

- src-tauri/src/assistant/mod.rs
- src-tauri/src/server/http_client.rs
- src/components/Assistant/Chat.tsx
> fix: query args in chat

- src/components/Search/ContextMenu.tsx
- src/components/Search/Search.tsx
- src/components/Search/SearchListItem.tsx
- src/hooks/useOSKeyPress.ts
- src/stores/searchStore.ts
> feat: search content added to context menu

- src/components/Search/ContextMenu.tsx
- src/components/Search/DropdownList.tsx
- src/components/Search/Search.tsx
- src/pages/main/index.tsx
- src/stores/searchStore.ts
improved the interaction of the search content context menu
> refactor: improved the interaction of the search content context menu

- src/pages/main/index.tsx
> refactor: window loses focus to hide the window

- src/components/Search/InputBox.tsx
> refactor: optimize networking search icon border

- src/components/Search/ContextMenu.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
> refactor: search content context menu internationalization

- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatHeader.tsx
- src/components/Assistant/Sidebar.tsx
- src/components/ChatMessage/MessageActions.tsx
- src/components/ChatMessage/QueryIntent.tsx
- src/components/ChatMessage/index.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
> chore: add suggestion

- src/components/Cloud/Cloud.tsx
- src/components/Cloud/DataSourceItem2.tsx
- src/components/Cloud/DataSourcesList.tsx
- src/components/Cloud/Sidebar.tsx
chore: server error update status
> chore: server error update status

- src-tauri/src/common/assistant.rs
> chore: update the response of new chat

- src/components/Search/InputExtra.tsx
> refactor: fixed window when uploading files

- src/components/Search/FileList.tsx
> refactor: file name overflow hiding in file list

- src/components/Cloud/DataSourcesList.tsx
> style: commented out unused code

- .github/workflows/release.yml
> chore: macOS code signing

- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatHeader.tsx
- src/components/Assistant/Greetings.tsx
- src/components/ChatMessage/QueryIntent.tsx
- src/components/Search/InputBox.tsx
- src/locales/zh/translation.json
- src/pages/chat/index.tsx
- src/pages/main/index.tsx
- src/stores/chatStore.ts
chore: Coco chat window input and message
> chore: Coco chat window input and message

- src/components/Search/FileList.tsx
- src/components/Search/InputBox.tsx
- src/components/Search/InputExtra.tsx
> refactor: change the style of the chat function buttons

- src/components/Assistant/Chat.tsx
- src/components/ChatMessage/DeepRead.tsx
- src/components/ChatMessage/FetchSource.tsx
- src/components/ChatMessage/PickSource.tsx
- src/components/ChatMessage/QueryIntent.tsx
- src/icons/Reading.tsx
- src/icons/Retrieve.tsx
- src/icons/Selection.tsx
- src/icons/Understand.tsx
chore: icon file & history message
> chore: icon file & history message

- package.json
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/capabilities/default.json
- src-tauri/src/lib.rs
- src/components/Settings/GeneralSettings.tsx
- src/main.tsx
- src/routes/layout.tsx
> refactor: use tauri's own method to switch themes

- src/components/Search/InputBox.tsx
- src/components/Search/InputExtra.tsx
optimize the style of the list of networking search services
> refactor: optimize the style of the list of networking search services

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/lib.rs
- src-tauri/src/local/application.rs
supports app search across all platforms
> feat: supports app search across all platforms

- src-tauri/src/lib.rs
- src-tauri/src/local/application.rs
> refactor: handling the use of unwrap

- src/components/Assistant/Chat.tsx
- src/components/ChatMessage/DeepRead.tsx
- src/components/ChatMessage/FetchSource.tsx
- src/components/ChatMessage/PickSource.tsx
- src/components/ChatMessage/QueryIntent.tsx
- src/components/ChatMessage/Think.tsx
- src/components/ChatMessage/index.tsx
- src/hooks/useChatActions.ts
- src/hooks/useMessageChunkData.ts
- src/hooks/useWebSocket.ts
refactor: chat code & chat loading
> refactor: chat code & chat loading

- package.json
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
> chore: update version to v0.2

- src/components/Assistant/Chat.tsx
- src/components/Common/Search.tsx
- src/components/Search/InputBox.tsx
- src/components/Search/Search.tsx
- src/pages/chat/index.tsx
> chore: not login deal

- src/components/ChatMessage/SuggestionList.tsx
- src/components/Cloud/Cloud.tsx
- src/components/Cloud/DataSourceItem.tsx
- src/components/Cloud/DataSourcesList.tsx
- src/components/Settings/GeneralSettings.tsx
> fix: suggestion list width

- src/components/Search/ContextMenu.tsx
> refactor: execute the right-click menu function to hide the window

- .vscode/settings.json
- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatHeader.tsx
- src/components/ChatMessage/QueryIntent.tsx
- src/components/Cloud/Cloud.tsx
- src/components/Search/InputBox.tsx
- src/components/Search/SearchPopover.tsx
fix: dataSourceList all & login async
> fix: dataSourceList all & login async

- package.json
- pnpm-lock.yaml
- src-tauri/capabilities/default.json
- src-tauri/src/lib.rs
- src/components/Settings/GeneralSettings.tsx
- src/hooks/useTray.ts
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/pages/main/index.tsx
- src/pages/settings/index.tsx
- src/stores/appStore.ts
> feat: tray internationalization and shortcut display

- src/pages/main/index.tsx
> refactor: add a border to the main window of linux only

- package.json
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src/components/Search/ContextMenu.tsx
> refactor: right-click again to close the context menu

- src/components/Assistant/Chat.tsx
> fix: chat error

- src/components/Search/InputBox.tsx
> refactor: hide file uploads

- src/components/Search/InputBox.tsx
> style: delete useless import

- src/components/Assistant/ChatHeader.tsx
> fix: ws link

- package.json
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
> chore: fallback version

- src/components/Assistant/ConnectPrompt.tsx
- src/components/Cloud/DataSourceItem.tsx
- src/components/Settings/AboutView.tsx
- src/routes/layout.tsx
- src/stores/themeStore.ts
> refactor: optimized theme switching

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/lib.rs
- src-tauri/src/server/auth.rs
- src-tauri/src/server/servers.rs
> fix: fusion search should excluded disabled servers

- src/components/Search/ContextMenu.tsx
> refactor: window not hidden after copying

- package.json
- pnpm-lock.yaml
- src-tauri/Info.plist
- src/components/Search/InputBox.tsx
- src/components/SpeechToText/index.tsx
- src/pages/main/index.tsx
> feat: chat supports voice input

- src/components/SpeechToText/index.tsx
> refactor: disable manual input during voice input

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/common/server.rs
> fix: incorrect version type

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/server/websocket.rs
- src/components/Assistant/Chat.tsx
- src/components/ChatMessage/QueryIntent.tsx
- src/components/ChatMessage/markdown.css
- src/hooks/useMessageHandler.ts
> fix: chat end type

- src/components/SpeechToText/index.tsx
> refactor: optimize voice input

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/DocumentList.tsx
- src/components/Search/DropdownList.tsx
- src/components/Search/Footer.tsx
- src/components/Search/Search.tsx
- src/utils/index.ts
> chore: remove selected function

- src/components/Search/SearchPopover.tsx
> refactor: optimize the outline of the button

- docs/content.en/docs/release-notes/_index.md
- src/hooks/useMessageHandler.ts
> chore: websocket timeout increased to 2 minutes

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/InputBox.tsx
- src/components/SpeechToText/index.tsx
> refactor: hide voice input buttons

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/InputBox.tsx
- src/pages/chat/index.tsx
> chore: chat input border & clear input

- docs/content.en/docs/release-notes/_index.md
- src/stores/connectStore.ts
> fix: store data is not shared among multiple windows

- src/stores/connectStore.ts
> refactor: resolving code conflicts

- .gitignore
- src/pages/chat/index.tsx
- src/pages/web/SearchChat.tsx
> chore: remove lazy

- src-tauri/src/autostart.rs
- src-tauri/src/lib.rs
- src-tauri/src/server/http_client.rs
- src-tauri/src/server/search.rs
- src-tauri/src/server/servers.rs
- src-tauri/src/server/websocket.rs
- src-tauri/src/shortcut.rs
- src-tauri/tauri.conf.json
> refactor: all commands methods have been changed to asynchronous

- src-tauri/src/assistant/mod.rs
- src-tauri/src/common/assistant.rs
- src-tauri/src/common/register.rs
- src-tauri/src/common/search.rs
- src-tauri/src/common/traits.rs
- src-tauri/src/lib.rs
- src-tauri/src/server/connector.rs
- src-tauri/src/server/datasource.rs
- src-tauri/src/server/http_client.rs
- src-tauri/src/server/search.rs
- src-tauri/src/server/servers.rs
- src-tauri/src/server/websocket.rs
> chore: eliminate all warnings for rust

- src-tauri/src/lib.rs
- src-tauri/src/shortcut.rs
- src/utils/platformAdapter.ts
> refactor: encapsulates show and hide methods

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/local/application.rs
> refactor: hide apps without icon

- src-tauri/src/lib.rs
- src-tauri/src/server/mod.rs
- src-tauri/src/server/transcription.rs
- src/api/transcription.ts
- src/components/Assistant/ChatContent.tsx
- src/components/Assistant/FileList.tsx
- src/components/AudioRecording/index.tsx
- src/components/Common/Icons/FileIcon/index.tsx
- src/components/Search/SearchPopover.tsx
> refactor: added the voice to text api

- src/components/Settings/Advanced/components/Shortcuts/index.tsx
> refactor: different platforms support different modifier keys

- src/components/Search/InputBox.tsx
> refactor: hide voice input and file upload functions

- docs/content.en/docs/release-notes/_index.md
> docs: update changelog

- src/components/Search/InputBox.tsx
> style: commenting out unused variables

- src/components/Common/HistoryList/index.tsx
- src/main.css
> refactor: disable outline for all elements

- README.md
- docs/content.en/_index.md
- docs/content.en/docs/_index.md
> chore: update preview

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/local/application.rs
- src/components/Search/ContextMenu.tsx
> feat: linux support for application search

- src/routes/layout.tsx
- src/stores/appStore.ts
- src/utils/platformAdapter.ts
> chore: app css & utils

- src/components/SearchChat/index.tsx
- src/utils/platformAdapter.ts
> style: compatible with css style

- docs/content.en/docs/release-notes/_index.md
- src/components/ChatMessage/DeepRead.tsx
- src/components/ChatMessage/FetchSource.tsx
- src/components/ChatMessage/PickSource.tsx
- src/components/ChatMessage/QueryIntent.tsx
- src/components/ChatMessage/Think.tsx
- src/components/Search/DocumentList.tsx
- src/hooks/useWebSocket.ts
- src/routes/layout.tsx
- src/utils/index.ts
- src/utils/platformAdapter.ts
- src/utils/tauriAdapter.ts
- src/utils/wrappers/tauriWrappers.ts
> chore: optimizing the code

- src/components/Settings/Advanced/components/Shortcuts/index.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
> refactor: improvement of internationalization content

- .vscode/settings.json
- src/components/Assistant/ChatHeader.tsx
- src/components/AudioRecording/index.tsx
- src/components/Common/Icons/FontIcon.tsx
- src/components/Search/InputBox.tsx
- src/hooks/useScript.ts
- src/main.css
- src/utils/platformAdapter.ts
- src/web.css
> fix: load app & web utils

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/Search.tsx
> fix: fixed the problem of not being able to search in secondary directories

- src/utils/index.ts
> fix: fix apps and articles not opening

- src/utils/index.ts
> refactor: replacing the open method

- index.html
- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatSidebar.tsx
- src/hooks/useChatActions.ts
- src/pages/chat/index.tsx
- src/routes/layout.tsx
- tailwind.config.js
> refactor: replace the history list in the main window

- package.json
- pnpm-lock.yaml
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/capabilities/default.json
- src-tauri/src/lib.rs
- src-tauri/src/setup/windows.rs
- src/components/SearchChat/index.tsx
> feat: add a border to the main window in Windows 10

- src/pages/chat/index.tsx
Fixes issues as shown in the video
https://github.com/user-attachments/assets/ff5a156a-9947-494a-9806-b7ccc1d61acf
> refactor: fix chat window style issues

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/lib.rs
- src-tauri/src/local/application.rs
> feat: expose applications::get_default_search_paths

- .env
- .vscode/settings.json
- docs/content.en/docs/release-notes/_index.md
- src-tauri/capabilities/default.json
- src/api/axiosRequest.ts
- src/components/Assistant/Chat.tsx
- src/components/ChatMessage/FetchSource.tsx
- src/components/Common/UI/Footer.tsx
- src/components/Common/UI/NoResults.tsx
- src/components/Search/ListRight.tsx
- src/components/Search/SearchHeader.tsx
- src/components/SearchChat/index.tsx
- src/hooks/useChatActions.ts
- src/pages/web/README.md
- src/pages/web/index.tsx
- src/routes/layout.tsx
- src/utils/platformAdapter.ts
- src/utils/tauriAdapter.ts
- src/utils/webAdapter.ts
- tsup.config.ts
> fix: active shadow setting

- src-tauri/src/local/application.rs
- src-tauri/src/server/auth.rs
- src/components/SearchChat/index.tsx
> refactor: displays the default mode when the app is launched for the first time

- src/components/Search/SearchPopover.tsx
- src/components/Settings/Advanced/components/Shortcuts/index.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/pages/main/index.tsx
- src/stores/shortcutsStore.ts
> feat: add a shortcut to open a network search scope

- src/components/Common/HistoryList/index.tsx
https://github.com/user-attachments/assets/ea08ab90-cdad-4533-86dc-90dd25ddde4c
> refactor: add autofocus to input boxes and block menu item default events

- src/components/Cloud/Cloud.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/pages/main/index.tsx
> chore: add translate

- src/components/Assistant/Chat.tsx
- src/hooks/useChatActions.ts
- src/pages/chat/index.tsx
> refactor: optimize history deletion

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/ChatHeader.tsx
- src/components/Common/VisibleKey.tsx
> feat: service list popup box supports keyboard-only operation

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/local/application.rs
> feat: impl list_app_with_metadata_in()

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/Chat.tsx
- src/components/Common/HistoryList/index.tsx
- src/hooks/useChatActions.ts
- src/pages/chat/index.tsx
> refactor: optimized history search and renaming

- src/types/platform.ts
- src/utils/platformAdapter.ts
- src/utils/tauriAdapter.ts
- src/utils/webAdapter.ts
> refactor: unify platform adapter interfaces and optimize code structure

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/server/datasource.rs
- src-tauri/src/server/servers.rs
- src/components/Common/VisibleKey.tsx
- src/components/Search/InputBox.tsx
- src/components/Search/SearchPopover.tsx
- src/components/SearchChat/index.tsx
- src/hooks/useModifierKeyPress.ts
- src/hooks/useSyncStore.ts
- src/pages/chat/index.tsx
- src/pages/main/index.tsx
- src/pages/web/index.tsx
- src/routes/layout.tsx
> feat: networked search data sources support search and keyboard-only operation

- src/components/Search/SearchPopover.tsx
> refactor: optimization of search box styles for networked search data sources

- src/components/Search/InputBox.tsx
- src/components/Settings/Advanced/components/Shortcuts/index.tsx
> refactor: disable system shortcuts

- src/components/Common/VisibleKey.tsx
- src/components/Search/InputBox.tsx
- src/constants/index.ts
- src/hooks/useModifierKeyPress.ts
- src/stores/shortcutsStore.ts
https://github.com/user-attachments/assets/a154caab-f53b-4d6b-8906-a92e31b8f2cf
> refactor: shortcuts take effect in the popup box when opening the popup box

- src/components/Search/InputBox.tsx
> style: remove unused code

- src/components/Search/DocumentList.tsx
- src/components/Search/SearchListItem.tsx
- src/pages/web/index.tsx
> style: dark bg color

- src/components/Assistant/ChatHeader.tsx
> refactor: add shortcut key hints to data source list

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/lib.rs
- src-tauri/src/local/application.rs
- src/components/Settings/Extensions/components/Accordion/index.tsx
- src/components/Settings/Extensions/components/Content/Applications/index.tsx
- src/components/Settings/Extensions/components/Details/Application/index.tsx
- src/components/Settings/Extensions/components/Details/Applications/index.tsx
- src/components/Settings/Extensions/index.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/pages/settings/index.tsx
- src/stores/applications.ts
- src/utils/tauriAdapter.ts
> feat: add application management to the plugin

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/DocumentDetail.tsx
- src/components/Search/ListRight.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
> style: search list details display

- package.json
- pnpm-lock.yaml
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/local/application.rs
- src/components/Settings/Extensions/index.tsx
- src/pages/chat/index.tsx
- src/pages/settings/index.tsx
- src/stores/chatStore.ts
- src/utils/tauriAdapter.ts
> refactor: upgrade `tauri-plugin-fs-pro` version and optimize code

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/ChatHeader.tsx
- src/components/ChatMessage/FetchSource.tsx
- src/components/Common/UI/Footer.tsx
- src/components/Common/UI/NoResults.tsx
- src/components/Common/VisibleKey.tsx
- src/components/Search/DocumentDetail.tsx
- src/components/Search/DropdownList.tsx
- src/components/Search/InputBox.tsx
- src/components/Search/ListRight.tsx
- src/components/Search/SearchHeader.tsx
- src/components/Search/SearchListItem.tsx
- src/components/Search/SearchPopover.tsx
- src/components/SearchChat/index.tsx
- src/hooks/useIsMobile.ts
- src/pages/web/index.tsx
- tailwind.config.js
> style: search data display

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/ChatHeader.tsx
- src/components/Assistant/ChatSidebar.tsx
- src/components/AudioRecording/index.tsx
- src/components/Common/HistoryList/index.tsx
- src/components/Common/UI/Footer.tsx
- src/components/Common/VisibleKey.tsx
- src/components/Search/InputBox.tsx
- src/components/Search/SearchPopover.tsx
- src/constants/index.ts
> feat: add keyboard-only operation to history list

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/assistant/mod.rs
- src-tauri/src/common/error.rs
- src-tauri/src/common/http.rs
- src-tauri/src/common/mod.rs
- src-tauri/src/common/search.rs
- src-tauri/src/common/traits.rs
- src-tauri/src/local/application.rs
- src-tauri/src/search/mod.rs
- src-tauri/src/server/attachment.rs
- src-tauri/src/server/http_client.rs
- src-tauri/src/server/profile.rs
- src-tauri/src/server/search.rs
- src-tauri/src/server/servers.rs
- src-tauri/src/server/transcription.rs
> refactor: refactoring api error handling

- src-tauri/src/local/application.rs
- src/components/Common/Icons/ItemIcon.tsx
- src/utils/tauriAdapter.ts
- src/utils/webAdapter.ts
> refactor: replace the app icon after search with an absolute path

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/local/application.rs
Fix the app search on Linux:
1. Correct the displayed app name
2. Add support for apps installed via Flatpak
> fix: linux app search

- src/commands/servers.ts
- src/components/ChatMessage/PrevSuggestion.tsx
- src/components/Common/ErrorNotification/index.tsx
- src/components/Common/HistoryList/index.tsx
- src/components/Search/SearchPopover.tsx
- src/hooks/useChatActions.ts
- src/hooks/useWebSocket.ts
- src/routes/index.tsx
- src/utils/tauriAdapter.ts
- src/utils/wrappers/tauriWrappers.ts
> chore: debug the code

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/server/attachment.rs
> fix: get attachments in chat sessioins

- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatContent.tsx
- src/components/Assistant/ChatSidebar.tsx
- src/components/Common/HistoryList/index.tsx
- src/components/Common/Icons/ItemIcon.tsx
- src/components/Common/VisibleKey.tsx
- src/components/Search/DropdownList.tsx
- src/components/Search/ListRight.tsx
- src/components/Search/SearchPopover.tsx
- src/components/Settings/Extensions/components/Details/Application/index.tsx
- src/hooks/useSyncStore.ts
- src/stores/shortcutsStore.ts
> refactor: optimization misc issues

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/assistant/mod.rs
- src-tauri/src/common/search.rs
- src-tauri/src/lib.rs
- src/commands/servers.ts
- src/components/Assistant/AssistantList.tsx
- src/components/Assistant/ChatHeader.tsx
- src/components/Assistant/ServerList.tsx
- src/components/ChatMessage/DeepRead.tsx
- src/components/ChatMessage/PickSource.tsx
- src/components/ChatMessage/QueryIntent.tsx
- src/components/ChatMessage/index.tsx
- src/components/Cloud/Cloud.tsx
- src/components/Cloud/Sidebar.tsx
- src/components/Search/DocumentDetail.tsx
- src/hooks/useChatActions.ts
- src/hooks/useClickAway.ts
- src/stores/connectStore.ts
- src/utils/wrappers/tauriWrappers.ts
Closing  https://github.com/infinilabs/coco-app/issues/159
> feat: add support for switching AI assistants

- docs/content.en/docs/release-notes/_index.md
- src/utils/webAdapter.ts
- tsup.config.ts
> build: build web components and publish

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/DropdownList.tsx
> refactor: optimize the style of the calculator

- src/components/Search/SearchPopover.tsx
> refactor: add empty data prompt to search scope

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/Calculator.tsx
- src/components/Search/ContextMenu.tsx
> feat: add keyboard event handling and double-click copying

- src/components/Assistant/AssistantList.tsx
- src/components/Settings/Advanced/components/Shortcuts/index.tsx
- src/constants/index.ts
- src/hooks/useSyncStore.ts
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/stores/shortcutsStore.ts
> feat: ai assistant supports shortcuts

- src/components/Search/DropdownList.tsx
- src/components/Search/InputBox.tsx
- src/hooks/useEscape.ts
> feat: support esc to exit right-click menu

- src/components/Assistant/Chat.tsx
> fix: current conversation tip

- src/components/Search/ContextMenu.tsx
> refactor: right-click menu returns to execute whichever one is selected

- src/components/Search/Calculator.tsx
- src/components/Search/DropdownList.tsx
- src/components/Search/ListRight.tsx
- src/components/Search/SearchListItem.tsx
> refactor: change the selected background color of the item

- src-tauri/src/lib.rs
- src-tauri/src/server/mod.rs
- src-tauri/src/server/system_settings.rs
- src/api/axiosRequest.ts
- src/components/Assistant/AssistantList.tsx
- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatContent.tsx
- src/components/Assistant/Splash.tsx
- src/components/ChatMessage/index.tsx
- src/components/Search/InputBox.tsx
- src/stores/connectStore.ts
- src/utils/platformAdapter.ts
- vite.config.ts
> feat: add chat mode launch page

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/Splash.tsx
> feat: add chat mode launch page #424

- src-tauri/src/assistant/mod.rs
- src/api/axiosRequest.ts
- src/components/Assistant/AssistantList.tsx
- src/constants/index.ts
- src/locales/en/translation.json
- src/locales/zh/translation.json
> feat: ai assistant supports search and paging

- src/components/Search/InputBox.tsx
- src/components/SearchChat/index.tsx
- src/hooks/useWindowEvents.ts
- src/stores/appStore.ts
> feat: auto becomes semi-transparent when it loses focus

- src-tauri/src/lib.rs
Tauri creates a global Tokio runtime in the backend Rust core process, and it is exposed via APIs under the module [`async_runtime`](https://docs.rs/tauri/latest/tauri/async_runtime/index.html), which means we can just use it instead of creating our own runtime when needed.
> refactor: use the Runtime created by tauri

- src-tauri/src/assistant/mod.rs
> chore: update response handle

- src/components/Assistant/AssistantList.tsx
- src/components/Common/PopoverInput.tsx
- src/components/Search/InputBox.tsx
- src/components/Search/MCPPopover.tsx
- src/components/Search/SearchPopover.tsx
- src/hooks/useEscape.ts
- src/pages/main/index.tsx
- src/pages/web/index.tsx
- src/utils/tauriAdapter.ts
> refactor: optimized the logic of esc key handling

- src/components/Assistant/AssistantList.tsx
- src/components/Assistant/ServerList.tsx
> refactor: optimized the up and down keys

- src/components/Search/InputBox.tsx
- src/components/Search/MCPPopover.tsx
- src/components/Settings/Advanced/components/Shortcuts/index.tsx
- src/hooks/useShortcutEditor.ts
- src/hooks/useSyncStore.ts
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/stores/shortcutsStore.ts
> feat: add MCP search-related shortcut configurations

- src/api/axiosRequest.ts
- src/components/Assistant/AssistantList.tsx
- src/components/ChatMessage/index.tsx
- src/components/Common/HistoryList/index.tsx
- src/components/Common/Icons/FontIcon.tsx
- src/hooks/useScript.ts
- src/pages/web/index.tsx
- src/utils/platformAdapter.ts
- tsup.config.ts
> chore: icons border color

- src/components/Assistant/AssistantList.tsx
- src/components/Search/ContextMenu.tsx
> feat: right-click menu search supports shortcuts

- src/components/Assistant/ChatHeader.tsx
- src/components/Assistant/Splash.tsx
- src/locales/en/translation.json
- src/routes/layout.tsx
> refactor: removed the selection effect

- src/pages/web/index.tsx
> feat: add useEscape and useModifierKeyPress hooks

- src/pages/web/index.tsx
> reactor: replacing the default key

- src/components/Settings/Advanced/index.tsx
- src/hooks/useSyncStore.ts
- src/stores/connectStore.ts
> refactor: rename queryTimeoutRenamed to querySourceTimeout

- src/components/Assistant/AssistantList.tsx
- src/components/Assistant/Splash.tsx
- src/components/Common/UI/Footer.tsx
- src/components/Common/UI/NoResults.tsx
- src/components/Search/DropdownList.tsx
- src/components/SearchChat/index.tsx
- src/components/Settings/Extensions/components/Content/Applications/index.tsx
- src/components/Settings/Extensions/components/Details/Application/index.tsx
- src/components/Settings/Extensions/components/Details/Applications/index.tsx
- src/components/Settings/Extensions/index.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
> refactor: fixing and optimizing known bugs

- src/components/Search/MCPPopover.tsx
> refactor: mcp list adaptation font icon

- src/components/Search/DocumentList.tsx
- src/components/Search/Search.tsx
> refactor: optimizing parameter variables

- .env
- tsup.config.ts
> build: build web 1.1.14

- docs/content.en/docs/release-notes/_index.md
This PR create by  to updates the release notes.
> chore: update release notes for publish 0.4.0-2018

- src-tauri/src/setup/mac.rs
> refactor: modifying the macos window level

- src/components/SearchChat/index.tsx
- src/pages/chat/index.tsx
> refactor: optimized getting data sources and mcp lists

- src/components/Assistant/Chat.tsx
- src/components/Assistant/types.ts
- src/components/ChatMessage/index.tsx
- src/hooks/useChatActions.ts
- src/pages/chat/index.tsx
- src/pages/main/index.tsx
- tsup.config.ts
> chore: historical message corresponding assistant

- src/components/Search/InputBox.tsx
- tsup.config.ts
> fix: deep_think param type

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/AutoResizeTextarea.tsx
- src/components/Search/InputBox.tsx
> fix: fixed carriage return problem with chinese input method

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/AssistantList.tsx
- src/components/Assistant/SessionFile.tsx
- src/components/ChatMessage/PrevSuggestion.tsx
- src/components/Common/HistoryList/index.tsx
- src/components/Search/ContextMenu.tsx
- src/components/Search/MCPPopover.tsx
- src/components/Search/SearchPopover.tsx
- src/components/Settings/Extensions/components/Details/Application/index.tsx
- src/components/Settings/Extensions/components/Details/Applications/index.tsx
> feat: check or enter to close the list of assistants

- docs/content.en/docs/getting-started/installation/ubuntu.md
document how to install Coco app on Ubuntu
> docs: document how to install Coco app on Ubuntu

- src/components/Search/InputBox.tsx
> feat: supports `Shift + Enter` input box line feeds

- src/components/SearchChat/index.tsx
- src/reducers/appReducer.ts
> refactor: optimize the mode display of the first launched window

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/ChatContent.tsx
- src/components/Common/Tooltip/index.tsx
- src/components/Search/DropdownList.tsx
- src/components/Search/Search.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
> chore: adjust list error message

- docs/content.en/docs/release-notes/_index.md
- src/api/axiosRequest.ts
- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatContent.tsx
- src/components/Assistant/ChatSidebar.tsx
- src/components/Assistant/ServerList.tsx
- src/components/ChatMessage/markdown.scss
- src/components/Common/HistoryList/index.tsx
- src/hooks/useChatActions.ts
- src/hooks/useMessageChunkData.ts
- src/hooks/useMessageHandler.ts
- src/hooks/useWebSocket.ts
- src/main.tsx
- src/pages/chat/index.tsx
> fix: Solve the problem of modifying the assistant in the chat

- src/components/Assistant/Chat.tsx
- src/components/ChatMessage/FetchSource.tsx
> build: solve build error

- docs/content.en/docs/release-notes/_index.md
- package.json
- pnpm-lock.yaml
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src/components/SearchChat/index.tsx
- src/components/Settings/Advanced/components/Appearance/index.tsx
- src/components/Settings/Advanced/components/UpdateSettings/index.tsx
- src/components/Settings/Advanced/index.tsx
- src/hooks/useSyncStore.ts
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/stores/appearance.ts
- src/utils/tauriAdapter.ts
Closes: https://github.com/infinilabs/coco-app/issues/478
> feat: support for snapshot version updates

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/lib.rs
- src/components/SearchChat/index.tsx
> fix: fix the focusing problem of the input box in windows

- .gitignore
- src/components/Search/MCPPopover.tsx
- src/pages/web/index.tsx
> chore: debug datasource component

- docs/content.en/docs/release-notes/_index.md
- src/components/Common/HistoryList/index.tsx
- src/hooks/useEscape.ts
- src/utils/index.ts
- src/utils/tauriAdapter.ts
> feat: history list add put away button

- docs/content.en/docs/release-notes/_index.md
- src/locales/en/translation.json
- src/locales/zh/translation.json
> chore: refine wording for search failure

- src/components/Assistant/ChatSidebar.tsx
> refactor: optimize the style of the sidebar

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/ChatContent.tsx
> feat: the chat content has added a button to return to the bottom

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/ChatContent.tsx
- src/components/Assistant/ChatSidebar.tsx
- src/components/Common/HistoryList/index.tsx
- src/components/Search/InputBox.tsx
- src/components/SearchChat/index.tsx
> chore: search and MCP show hidden logic

- docs/content.en/docs/release-notes/_index.md
- src/components/SearchChat/index.tsx
- src/pages/main/index.tsx
UpdateApp component is only loaded in app, not in web
> chore: UpdateApp component loading location

- docs/content.en/docs/release-notes/_index.md
- src/components/SearchChat/index.tsx
- src/pages/settings/index.tsx
> chore: add clear monitoring & cache calculation to optimize performance

- docs/content.en/docs/release-notes/_index.md
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/server/websocket.rs
> feat: websocket support self-signed TLS

- src/components/Settings/Extensions/components/Content/index.tsx
- src/components/Settings/Extensions/index.tsx
https://github.com/user-attachments/assets/af37b83f-4c5b-4216-ae47-39b5bd0ff846
> refactor: changing the timing of app list loading

- docs/content.en/docs/release-notes/_index.md
- src/components/Settings/Advanced/index.tsx
- src/hooks/useSyncStore.ts
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/stores/connectStore.ts
> feat: add option to allow self-signed certificates

- docs/content.en/docs/release-notes/_index.md
- src/components/Common/HistoryList/index.tsx
https://github.com/infinilabs/coco-app/issues/506
> fix: fixed the newly created session has no title when it is deleted

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/ChatIcons.tsx
- src/components/Search/InputBox.tsx
> style: chat input icons show

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/server/attachment.rs
- src/components/Assistant/SessionFile.tsx
> fix: loading chat history for potential empty attachments

- docs/content.en/docs/release-notes/_index.md
- src/components/ChatMessage/Markdown.tsx
- src/components/ChatMessage/markdown.scss
> refactor: optimizing list styles in markdown content

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/AssistantList.tsx
- src/components/Search/MCPPopover.tsx
- src/components/Search/SearchPopover.tsx
> fix: datasource & MCP list synchronization update

- .vscode/settings.json
- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/common/http.rs
- src-tauri/src/lib.rs
- src-tauri/src/server/datasource.rs
- src-tauri/src/server/http_client.rs
- src/components/Assistant/AssistantList.tsx
- src/components/SearchChat/index.tsx
> fix: show only enabled datasource & MCP list

- docs/content.en/docs/release-notes/_index.md
> docs: update notes

- src/pages/web/README.md
- src/utils/platformAdapter.ts
- tsup.config.ts
> build: build & publish web component

- src-tauri/src/server/datasource.rs
> fix: panic caused by an unwrap()

- src-tauri/tauri.conf.json
> chroe: update minimum macOS version to 10

- src-tauri/src/local/application/with_feature.rs
Fix issue where pressing an application hotkey opens two application windows.
When an application hotkey is pressed, the handler is triggered twice: once with event `ShortcutState::Pressed`, and once with event `ShortcutState::Released`. This PR fixes the issue by ensuring the application is only opened when the event is `ShortcutState::Pressed`.
> fix: application opened twice when hotkey gets pressed

- src-tauri/src/local/calculator.rs
The math expression evaluation library we use will **panic** if the passed query string is a string with only whitespace. After this PR, we no longer pass such strings to it.
> fix: do not pass whitespace-only strings to Calculator expr evaluation lib

- docs/content.en/docs/release-notes/_index.md
- src/components/Common/ErrorNotification/ErrorSearch.tsx
> style: search error styles

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/AssistantFetcher.tsx
- src/components/Assistant/AssistantList.tsx
- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatContent.tsx
- src/components/Assistant/ChatHeader.tsx
- src/components/Assistant/Splash.tsx
- src/components/Common/ScrollToBottom.tsx
- src/hooks/useChatActions.ts
> fix: switch server assistant and session session unchanged

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/common/error.rs
- src-tauri/src/common/http.rs
- src-tauri/src/search/mod.rs
- src-tauri/src/server/search.rs
> refactor: refactoring search error

- src-tauri/src/common/error.rs
- src-tauri/src/search/mod.rs
Clean up some dead code warnings.
> chore: dead code cleanup

- docs/content.en/docs/release-notes/_index.md
- src/commands/servers.ts
- src/components/Assistant/AssistantFetcher.tsx
- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatHeader.tsx
- src/components/Assistant/ServerList.tsx
- src/hooks/useChatActions.ts
- src/stores/authStore.ts
> chore: add global login judgment

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/server/search.rs
- src-tauri/src/server/servers.rs
> chore: mark server offline on user logout

- docs/content.en/docs/release-notes/_index.md
- src/components/Cloud/ServiceAuth.tsx
- src/types/server.ts
> chore: logout update server profile

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatSidebar.tsx
- src/components/SearchChat/index.tsx
> fix: history list height

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/Search.tsx
> fix: secondary page cannot be searched

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/ChatContent.tsx
> fix: the scroll button is not displayed by default

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/ChatHeader.tsx
- src/components/Search/DocumentDetail.tsx
- src/components/Search/InputBox.tsx
- src/components/SearchChat/index.tsx
- src/pages/chat/index.tsx
> fix: independent chat app has no datasources

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/AssistantItem.tsx
- src/components/Assistant/AssistantList.tsx
- src/components/Common/Pagination.tsx
- src/components/Search/MCPPopover.tsx
- src/components/Search/SearchPopover.tsx
> chore: assistant keyboard events and mouse events

- docs/content.en/docs/release-notes/_index.md
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/search/mod.rs
> feat: rerank search results

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/search/mod.rs
> chore: rerank support ignore case

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/assistant/mod.rs
- src-tauri/src/search/mod.rs
> refactor: refactoring rerank feature

- docs/content.en/docs/release-notes/_index.md
- src/components/Common/ChatSwitch.tsx
- src/components/Search/AssistantManager.tsx
- src/components/Search/InputBox.tsx
- src/components/Search/InputControls.tsx
- src/components/SearchChat/index.tsx
- src/hooks/useKeyboardHandlers.ts
- src/pages/chat/index.tsx
- src/types/chat.ts
> refactor: input box related components

- docs/content.en/docs/release-notes/_index.md
- src/components/Common/UI/Footer.tsx
- src/components/Search/AssistantManager.tsx
- src/components/Search/DropdownList.tsx
- src/components/Search/DropdownListItem.tsx
- src/components/Search/InputBox.tsx
- src/components/Search/Search.tsx
- src/components/Search/SearchIcons.tsx
- src/components/Search/SearchListItem.tsx
- src/components/Search/SearchSource.tsx
- src/components/SearchChat/index.tsx
- src/hooks/useKeyboardHandlers.ts
- src/hooks/useKeyboardNavigation.ts
- src/hooks/useSearch.ts
- src/types/search.ts
1. Fixed the bug of the keyboard events in this part
2. Refactored the components of the search area
> refactor: search result related components

- src/components/Search/DocumentList.tsx
- src/components/Search/DropdownList.tsx
- src/routes/layout.tsx
- src/utils/platformAdapter.ts
> fix: fix the problem that web cannot click on the jump

- src-tauri/src/server/servers.rs
> chore: update default coco server

- src/components/Settings/Extensions/index.tsx
> refactor: remove unused disabledExtensions related code

- src-tauri/src/common/search.rs
- src-tauri/src/search/mod.rs
- src-tauri/src/server/search.rs
- src-tauri/tauri.conf.json
> chore: update error handling

- src/components/Search/AssistantManager.tsx
> fix: sent chat once more

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/assistant/mod.rs
> chore: remove icon field before ask ai

- src-tauri/src/assistant/mod.rs
> chore: ignore throttle message

- src/components/Search/AskAi.tsx
- src/hooks/useSearch.ts
> fix: fixed issue with quick ai access making multiple requests at once

- src/components/Common/UI/Footer.tsx
- src/components/Common/UI/SettingsFooter.tsx
- src/components/Settings/AboutView.tsx
This pull request updates the application version displayed in various components from `v1.0.0` (or a fallback using `process.env.VERSION`) to a hardcoded `v0.5.2`. This ensures consistency in the displayed version across the application.
* [`src/components/Common/UI/Footer.tsx`](diffhunk://#diff-2fa8cfd44a8ebbd3220792d85fba4c7fc9571a6cd80cf083d7f16605e5386280L97-R97): Updated the version displayed in the footer to `"v0.5.2"`, replacing the previous usage of `process.env.VERSION` or the fallback `"v1.0.0"`.
* [`src/components/Common/UI/SettingsFooter.tsx`](diffhunk://#diff-fca4113679d3916ebc3fdb71bfcb75551e1b92809d0abf7c66462af971c69e27L86-R86): Changed the version displayed in the settings footer to `"v0.5.2"`, removing the dependency on `process.env.VERSION` and the fallback `"v1.0.0"`. …
> chore: use version fix

- src/components/ChatMessage/index.tsx
> fix: set chat message assistant

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/InputControls.tsx
- src/components/Settings/Advanced/components/Shortcuts/index.tsx
- src/hooks/useSyncStore.ts
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/stores/shortcutsStore.ts
> feat: ai overview support is enabled with shortcut

- src/components/Common/Icons/CommonIcon.tsx
> fix: app icon load console error

- src/utils/webAdapter.ts
> fix: web component icon loading issue

- docs/content.en/docs/release-notes/_index.md
- src/hooks/useChatActions.ts
> chore: initialize current assistant from history

- src/components/Common/VisibleKey.tsx
- src/components/Search/InputBox.tsx
- src/components/Search/InputControls.tsx
- src/stores/appStore.ts
- src/types/platform.ts
> fix: shortcut key prompts cannot be hidden

- src/components/Cloud/DataSourcesList.tsx
> fix: datasource refresh status feedback

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/Chat.tsx
- src/components/Common/HistoryList/index.tsx
- src/pages/chat/index.tsx
fixed an issue where renaming would sort to the top of the list
> fix: fix chat log update and sorting issues

- src/components/Search/MCPPopover.tsx
- src/components/Search/SearchPopover.tsx
> fix: datasource and mcp data updates

- src/hooks/useChatActions.ts
- src/pages/chat/index.tsx
> fix: only select history and then set the assistant

- src-tauri/src/extension/built_in/application/with_feature.rs
Fix the deserialization error when the input contains multiple lines. After this PR, newline characters will be successfully passed to Pizza and used for tokenization:
> fix: invalid DSL error if input contains multiple lines

- docs/content.en/docs/release-notes/_index.md
> chore: release note for PR 620

- src/hooks/useSearch.ts
> refactor: optimize data filtering logic

- src/stores/appearanceStore.ts
> refactor: optimized input box logic for transparency

- docs/content.en/docs/release-notes/_index.md
- src/components/Settings/Extensions/components/Details/AiOverview/index.tsx
- src/components/Settings/Extensions/components/Details/SharedAi/index.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
> feat: add internationalized translations of AI-related extensions

- src/components/SearchChat/index.tsx
- src/routes/layout.tsx
> fix: web component set IsDark

- src/components/SearchChat/index.tsx
> chore: web component default mode

- src/components/Assistant/AssistantFetcher.tsx
- src/components/Assistant/AssistantList.tsx
- src/components/Assistant/Chat.tsx
- src/components/Assistant/ServerList.tsx
- src/components/Assistant/Splash.tsx
- src/components/Settings/Advanced/index.tsx
- src/hooks/useChatActions.ts
- src/hooks/useSyncStore.ts
- src/pages/chat/index.tsx
- src/pages/settings/index.tsx
- src/stores/connectStore.ts
https://github.com/user-attachments/assets/fc83f7d1-f78e-4928-baaf-c4965aa67377
> refactor: improved page content after disabling the service

- src/components/Common/HistoryList/HistoryListContent.tsx
> fix: remove stopImmediatePropagation event

- src/hooks/useKeyboardHandlers.ts
> fix: add shift line break to chat input

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/AssistantManager.tsx
> fix: tab key hides window in chat mode

- docs/content.en/docs/release-notes/_index.md
- src/hooks/useKeyboardNavigation.ts
> fix: arrow keys still navigated search when menu opened with `Cmd+K`

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/ContextMenu.tsx
- src/components/Search/DropdownList.tsx
- src/components/Search/InputBox.tsx
- src/components/Search/Search.tsx
- src/components/SearchChat/index.tsx
- src/hooks/useKeyboardNavigation.ts
- src/pages/main/index.tsx
- src/pages/web/README.md
- src/pages/web/index.tsx
> fix: web page unmount event

- src/stores/connectStore.ts
> chore: remove default current service

- src/components/Common/HistoryList/HistoryListContent.tsx
- src/components/Common/HistoryList/HistoryListItem.tsx
> style: differentiate between hover and selected styles

- src/components/ChatMessage/UserMessage.tsx
> style: user message line break

- src/components/Common/HistoryList/HistoryListContent.tsx
- src/components/Common/HistoryList/HistoryListItem.tsx
- src/components/Search/AssistantManager.tsx
- src/hooks/useKeyboardHandlers.ts
> fix: stop event bubbling

- src/components/Search/AssistantManager.tsx
- src/hooks/useKeyboardHandlers.ts
> refactor: remove the behavior that organizes event bubbling

- src/components/Assistant/ServerList.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
> chore: add i18n to services

- src/components/Search/InputBox.tsx
- src/hooks/useKeyboardHandlers.ts
> chore: remove enter disabled

- src-tauri/src/common/document.rs
- src/components/Search/ContextMenu.tsx
- src/components/Search/DocumentList.tsx
- src/components/Search/DropdownList.tsx
- src/hooks/useKeyboardNavigation.ts
- src/types/platform.ts
- src/utils/tauriAdapter.ts
- src/utils/webAdapter.ts
> refactor: don't hide pinned window on search result open

- src/components/ChatMessage/MessageActions.tsx
- src/components/ChatMessage/index.tsx
- src/components/Search/AskAi.tsx
- src/constants/index.ts
> refactor: dynamically generated copy button id

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/AssistantList.tsx
- src/components/Cloud/Connect.tsx
- src/components/Common/HistoryList/HistoryListItem.tsx
- src/components/Common/HistoryList/index.tsx
- src/components/Common/PopoverInput.tsx
- src/components/Search/AutoResizeTextarea.tsx
- src/components/Search/ContextMenu.tsx
- src/components/Search/MCPPopover.tsx
- src/components/Search/SearchPopover.tsx
- src/components/Settings/SettingsInput.tsx
- src/utils/index.ts
> chore: add special character filtering

- src/components/Assistant/AssistantFetcher.tsx
> fix: web assistant list

- src/components/SearchChat/index.tsx
- src/components/Settings/GeneralSettings.tsx
- src/hooks/useSyncStore.ts
- src/pages/settings/index.tsx
- src/routes/layout.tsx
- src/stores/appStore.ts
- src/types/platform.ts
> refactor: optimize global state synchronization

- src/components/Common/VisibleKey.tsx
- src/components/Search/ChatIcons.tsx
> style: safari styles

- src/utils/index.ts
> fix: keep line breaks

- src/components/Search/InputControls.tsx
- src/components/Search/MCPPopover.tsx
- src/components/Search/SearchPopover.tsx
- src/components/SearchChat/index.tsx
- src/hooks/useChatActions.ts
- src/reducers/appReducer.ts
- src/utils/index.ts
> chore: search & deep think & mcp

- docs/content.en/docs/release-notes/_index.md
- src/hooks/useKeyboardNavigation.ts
- src/hooks/useSearch.ts
> fix: fix problem with up and down key indexing

- src/components/Settings/Extensions/components/Details/SharedAi/index.tsx
> fix: filter services for unlogged-in users

- src/components/Search/DocumentList.tsx
> refactor: optimize the timing of arrow key triggers on secondary pages

- src/components/Search/DocumentList.tsx
- src/components/Search/DropdownList.tsx
- src/components/Search/Search.tsx
> refactor: optimize the operation of the small assistant on the secondary page

- docs/content.en/docs/release-notes/_index.md
- src-tauri/Cargo.toml
- src-tauri/src/lib.rs
- src-tauri/src/shortcut.rs
> fix: arrow inserting escape sequences

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/AskAi.tsx
- src/components/Search/AssistantManager.tsx
- src/components/Settings/Extensions/index.tsx
> fix: quick ai state synchronous

- src/components/ChatMessage/UserMessage.tsx
- src/components/Common/HistoryList/HistoryListContent.tsx
- src/components/Search/AutoResizeTextarea.tsx
> chore: keeping windows and documents safe

- src/components/Common/UI/Footer.tsx
- src/components/Search/ExtensionStore.tsx
> refactor: show all extensions by default in the extension store

- src/components/Assistant/AssistantList.tsx
- src/components/Cloud/Connect.tsx
- src/components/Common/HistoryList/HistoryListItem.tsx
- src/components/Common/HistoryList/index.tsx
- src/components/Search/AutoResizeTextarea.tsx
- src/components/Search/ContextMenu.tsx
- src/components/Search/MCPPopover.tsx
- src/components/Search/SearchPopover.tsx
- src/components/Settings/SettingsInput.tsx
- src/utils/index.ts
The problem with arrow key input has been fixed by removing the code related to special character filtering.
> refactor: remove special character filtering and clean up related code

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/AssistantList.tsx
- src/components/Search/MCPPopover.tsx
- src/components/Search/SearchPopover.tsx
> fix: some input fields couldn’t accept spaces

- src-tauri/src/extension/store.rs
> chore: change extension store request URL to default coco server

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/ContextMenu.tsx
> fix: context menu search not working

- src/components/Search/ExtensionDetail.tsx
> refactor: update extension detail page ui

- src/components/Settings/Extensions/components/Details/Applications/index.tsx
> chore: rebuild index position

- src/components/Common/UI/Footer.tsx
> fix: text  display error

- src/components/Search/AssistantManager.tsx
- src/components/Search/Search.tsx
- src/components/SearchChat/index.tsx
> fix: open extension store display

- docs/content.en/docs/release-notes/_index.md
> chore: release notes for 0.6.0

- src/pages/settings/index.tsx
> fix: tray not on display

- .github/workflows/release.yml
> fix: build error on windows platform with cargo add git repo

- .github/workflows/release.yml
fixed feature dependcy local path
> fix: feature dependcy local path

- .github/workflows/release.yml
Fixed default shell for windows platform
> fix: windows platform run with shell

- src/components/UpdateApp/index.tsx
- src/stores/updateStore.ts
> fix: update information storage cache and styles

- src/components/Settings/Advanced/index.tsx
- src/components/Settings/SettingsInput.tsx
> fix: build error

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/common/search.rs
> chore: make optional fields optional

- src-tauri/src/server/attachment.rs
- src/components/Assistant/ChatContent.tsx
- src/components/Assistant/FileList.tsx
- src/components/Search/InputBox.tsx
- src/components/Search/InputControls.tsx
> refactor: updated the upload endpoint for attachments

- src/hooks/useScript.ts
> refactor: update the font icon link

- docs/content.en/docs/release-notes/_index.md
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/extension/mod.rs
- src-tauri/src/extension/third_party/mod.rs
- src-tauri/src/lib.rs
- src-tauri/src/server/http_client.rs
- src-tauri/src/util/app_lang.rs
- src-tauri/src/util/mod.rs
- src-tauri/src/util/platform.rs
- src/components/Settings/GeneralSettings.tsx
Add the following HTTP headers when making HTTP requests:
X-OS-NAME
X-OS-VER
X-OS-ARCH
X-APP-NAME
X-APP-VER
X-APP-LANG
> chore: Coco app http request headers

- src/components/Assistant/ChatContent.tsx
- src/components/Search/InputControls.tsx
> refactor: close the file upload port

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatContent.tsx
- src/components/ChatMessage/FetchSource.tsx
- src/components/ChatMessage/index.tsx
- src/components/SearchChat/index.tsx
- src/pages/web/index.tsx
- src/utils/platformAdapter.ts
- tsup.config.ts
> chore: search-chat add language and formatUrl parameters

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/Chat.tsx
- src/components/ChatMessage/index.tsx
- src/components/Search/AiOverview.tsx
- src/components/Search/AskAi.tsx
- src/hooks/useStreamChat.ts
- src/pages/main/index.tsx
> fix: resolved minor issues with voice playback

- docs/content.en/docs/release-notes/_index.md
- src-tauri/tauri.conf.json
- src-tauri/tauri.linux.conf.json
> fix: fixed incorrect taskbar icon display on linux

- src/hooks/useSyncStore.ts
> refactor: decouple window switch services to ensure they operate independently

- .vscode/settings.json
- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/assistant/mod.rs
- src-tauri/tauri.conf.json
- src-tauri/tauri.linux.conf.json
- src/commands/servers.ts
- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatContent.tsx
- src/components/ChatMessage/QueryIntent.tsx
- src/components/ChatMessage/UserMessage.tsx
- src/components/ChatMessage/index.tsx
- src/components/Search/DocumentList.tsx
- src/components/SearchChat/index.tsx
- src/hooks/useChatActions.ts
- src/hooks/useMessageHandler.ts
- src/pages/chat/index.tsx
- src/routes/index.tsx
- src/types/chat.ts
- src/types/platform.ts
> fixed:  chat message confusion

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/AssistantManager.tsx
- src/components/Search/InputBox.tsx
- src/hooks/useKeyboardHandlers.ts
> fix: enter key problem

- src-tauri/src/main.rs
> chore: add a panic hook to catch panic msg

- docs/content.en/docs/release-notes/_index.md
- src/components/Common/HistoryList/HistoryListItem.tsx
> fix: fix selection issue after renaming

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/AutoResizeTextarea.tsx
- src/components/Search/InputBox.tsx
> fix: fix multiline input issue

- src/components/UpdateApp/index.tsx
- src/hooks/useTray.ts
- src/pages/check/index.tsx
- src/types/platform.ts
> refactor: refactor version update check

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/lib.rs
- src-tauri/src/util/mod.rs
- src-tauri/src/util/updater.rs
> refactor: use custom version comparator to determine if we should update

- src/components/Assistant/Chat.tsx
- src/components/Assistant/ChatContent.tsx
- src/hooks/useChatActions.ts
- src/locales/en/translation.json
> fix：the client id is the same

- src/components/Search/InputBox.tsx
- src/components/Search/MCPPopover.tsx
- src/components/Search/SearchPopover.tsx
- src/hooks/useChatActions.ts
> chore: adjust cancel interface parameters

- src/components/UpdateApp/index.tsx
> refactor: optimize method calls for checking for updates

- src/components/Search/AssistantManager.tsx
> refactor: optimize carriage return copying

- src/components/Search/DocumentList.tsx
> refactor: optimize subpage shortcut context menu

- package.json
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
> chore: bump version number to 0.7.1

- docs/content.en/docs/release-notes/_index.md
- src/components/Common/UI/Footer.tsx
- src/components/UpdateApp/index.tsx
- src/stores/updateStore.ts
> feat: enhance ui for skipped version

- src-tauri/tauri.appstore.conf.json
- src-tauri/tauri.macos.conf.json
> chore: add macos config for tauri

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/Synthesize.tsx
- src/components/Common/Icons/FontIcon.tsx
- src/components/SearchChat/index.tsx
- src/components/Settings/Extensions/components/Details/Application/index.tsx
- src/hooks/useScript.ts
- src/hooks/useSearch.ts
- src/hooks/useTogglePin.ts
- src/pages/web/index.tsx
- src/routes/layout.tsx
- src/types/platform.ts
- src/utils/tauriAdapter.ts
- src/utils/webAdapter.ts
> chore: web component loading font icon

- src/components/Search/InputBox.tsx
- src/components/SearchChat/index.tsx
- src/utils/index.ts
> refactor: optimized sending messages

- src/components/AudioRecording/index.tsx
- src/components/Common/VisibleKey.tsx
- src/components/Search/ChatIcons.tsx
- src/components/Search/InputBox.tsx
> refactor: optimize enter key display

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
> fix: fix microphone permission issue

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/Chat.tsx
- src/components/SearchChat/index.tsx
- src/components/Settings/GeneralSettings.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/stores/authStore.ts
- src/types/platform.ts
> fix: web component login state

- docs/content.en/docs/release-notes/_index.md
- src/commands/servers.ts
- src/commands/windowService.ts
- src/components/Assistant/ServerList.tsx
- src/hooks/useServers.ts
- src/types/platform.ts
- src/utils/tauriAdapter.ts
- src/utils/webAdapter.ts
> build: web component build error

- .github/workflows/frontend-ci.yml
Adds build check for our frontend code
> ci: check frontend code by building it

- src-tauri/src/autostart.rs
- src-tauri/src/lib.rs
- src-tauri/src/setup/linux.rs
- src-tauri/src/setup/mac.rs
- src-tauri/src/setup/mod.rs
- src-tauri/src/setup/windows.rs
- src-tauri/src/shortcut.rs
- src-tauri/src/util/app_lang.rs
- src/components/UpdateApp/index.tsx
- src/pages/check/index.tsx
- src/routes/layout.tsx
- src/routes/outlet.tsx
- src/stores/appStore.ts
- src/types/platform.ts
> refactor: let frontend set up backend states to avoid races

- docs/content.en/docs/getting-started/installation/ubuntu.md
Update the installation document [1] to mention that we have some dynamic libraries that need to be installed as well.
[1]: https://docs.infinilabs.com/coco-app/main/docs/getting-started/installation/ubuntu/
> docs: doc dylib dependencies in install doc

- src/commands/servers.ts
- src/commands/windowService.ts
- src/components/Assistant/AssistantFetcher.tsx
- src/components/Assistant/Splash.tsx
- src/components/ChatMessage/MessageActions.tsx
- src/components/Search/InputBox.tsx
- src/components/Settings/Extensions/components/Details/SharedAi/index.tsx
- src/hooks/useChatActions.ts
- src/hooks/useSyncStore.ts
- src/pages/chat/index.tsx
- src/utils/index.ts
- src/utils/tauriAdapter.ts
> fix: fix ai extension assistant list fetch

- src-tauri/src/extension/third_party/install/store.rs
Now we send requests to the default Coco server.
> chore: update extension detail API URL

- docs/content.en/docs/release-notes/_index.md
- package.json
- pnpm-lock.yaml
- src/components/Search/ContextMenu.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/utils/tauriAdapter.ts
> feat: support opening file in its containing folder

- src/components/Search/ViewExtension.tsx
> chore: remove example iframe title
