- Makefile
This pull request introduces several new targets and checks to the `Makefile` to streamline the development and build process for a desktop application. The most important changes include setting a minimum Node.js version requirement, adding targets for installing dependencies, starting development, and building the application, and creating a clean rebuild process.
Makefile enhancements:
* Added a variable `NODE_VERSION_MIN` to specify the minimum required Node.js version.
* Introduced a `check-node-version` target to ensure the Node.js version meets the minimum requirement before proceeding.
* Added `install-dependencies` target to install necessary dependencies using `pnpm`.
* Created `start-dev`, `build-mac-app`, and `build-mac-dmg` targets to handle starting development and building …
> chore: add Makefile

- Makefile
This pull request includes changes to the `Makefile` to remove the `install-dependencies` step from the `build-mac-app` and `build-mac-dmg` targets. 
Changes to `Makefile`:
* Removed the `install-dependencies` step from the `build-mac-app` target.
* Removed the `install-dependencies` step from the `build-mac-dmg` target.
> chore: optimize makefile, don't call install-dependencies for each build

- src-tauri/tauri.conf.json
This pull request includes a small change to the `src-tauri/tauri.conf.json` file. The change adds two new properties to the configuration: `skipTaskbar` and `resizable`.
Configuration updates:
* [`src-tauri/tauri.conf.json`](diffhunk://#diff-fa09f1dac39604a735cd6a53957d3c35e0c3298cca9cf4829180f167abbd69b7R23-R24): Added `skipTaskbar` and `resizable` properties to the window configuration.
> feat: no task bar or resizable by default

- src/components/AppAI/InputBox.tsx
This pull request includes a small change to the `src/components/AppAI/InputBox.tsx` file. The change comments out a line that prevents the default action when the Meta key is pressed.
* [`src/components/AppAI/InputBox.tsx`](diffhunk://#diff-d6d676e884b2d9c7e9ae52426e13fb27efad5dd5ca7f2161ce38e71dd7d11868L84-R84): Commented out `e.preventDefault()` within the `if (pressedKeys.has("MetaLeft") || pressedKeys.has("MetaRight"))` block.
> fix: resolve search hang issue after multiple queries

- src/components/Search/DocumentList.tsx
- src/components/Search/DropdownList.tsx
- src/components/Search/InputBox.tsx
This pull request includes several changes to the `src/components/Search` directory, focusing on simplifying the CSS class names and adding a new icon import. The most important changes include the removal of conditional CSS classes, the addition of the `Search` icon, and the update to the conditional rendering logic in `InputBox`.
CSS class simplifications:
* [`src/components/Search/DocumentList.tsx`](diffhunk://#diff-4e1be6feaebf78efa35da33fc8fb0b66627b6a6a3e8dc5b98adb8f6dacaa74cdL202-R202): Removed conditional `font-medium` class from the `span` element.
* [`src/components/Search/DropdownList.tsx`](diffhunk://#diff-d6fe67fb47bf0b7901e66664c72431643ae09725bcd42aa7e0e43ef8b873c82cL196-R196): Simplified CSS classes by removing conditional classes for the `div` and `span` elements. …
> chore: update search style

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/Info.plist
- src-tauri/capabilities/default.json
- src-tauri/src/common/mod.rs
- src-tauri/src/lib.rs
- src-tauri/src/setup/linux.rs
- src-tauri/src/setup/mac.rs
- src-tauri/src/setup/mod.rs
- src-tauri/src/setup/windows.rs
- src-tauri/src/shortcut.rs
- src-tauri/tauri.conf.json
This pull request includes several changes to the `src-tauri` project, focusing on plugin updates, window management improvements, and platform-specific setup enhancements. The most important changes include updating the plugin configurations, adding new window labels and properties, and implementing platform-specific setup functions.
* Updated `Cargo.toml` to replace `tauri-plugin-oauth` with `tauri-nspanel`.
* Added `MAIN_WINDOW_LABEL` and `SETTINGS_WINDOW_LABEL` constants in `src-tauri/src/common/mod.rs` for better window management.
* Updated window-related functions to use the new window labels in `src-tauri/src/lib.rs`. [[1]](diffhunk://#diff-eabcebd0ae5c9b77a5247e1bdbdb88b1869fc0c932d0ef0cf2ecf9ee5221be7cL22-R31) [[2]](diffhunk://#diff-eabcebd0ae5c9b77a5247e1bdbdb88b1869fc0c932d0ef0 …
> fix: ensure app is always on top and visible on all workspaces

- src/contexts/ThemeContext.tsx
Key Improvements:
1.	Prevent Duplicate Theme Changes:
•	We keep track of the lastAppliedTheme in the state to prevent applying the same theme repeatedly.
•	Before applying a theme, we check if it’s different from the last applied theme.
2.	No Unnecessary Event Handling:
•	By debouncing or simply checking for theme differences, we avoid unnecessary calls to applyTheme, which would previously fire multiple times in rapid succession if the theme changes multiple times quickly.
3.	Correct Cleanup:
•	The event listener for the system theme change (mediaQuery.addEventListener) is correctly cleaned up in the useEffect cleanup function.
Notes:
•	The changeTheme function is now more efficient because it prevents setting the same theme repeatedly.
•	The lastAppliedTheme state ensures that …
> fix: resolve theme change handling

- src-tauri/src/lib.rs
- src-tauri/src/main.rs
- src-tauri/src/shortcut.rs
- src-tauri/tauri.conf.json
- src/main.css
This pull request includes several changes to the `src-tauri/src/lib.rs` file to improve the application's initialization and window management processes. The most important changes include adding a new function to move the application window to the active monitor, running initialization tasks in the background, and making minor adjustments to function calls and imports.
* Added the `move_window_to_active_monitor` function to move the application window to the active monitor when the "Open Coco" menu is clicked. This function handles monitor detection and cursor position gracefully. (`src-tauri/src/lib.rs`)
* Updated the `handle_open_coco` function to call `move_window_to_active_monitor` before showing the window and setting its properties. (`src-tauri/src/lib.rs`)
* Cloned `app_handle` …
> feat: allow to launch coco across multi monitors

- Makefile
- docs/content.en/docs/release-notes/_index.md
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/capabilities/default.json
- src-tauri/src/lib.rs
- src-tauri/tauri.conf.json
Handle proper permission setting, remove whitespace from output's product name.
Passed for AppImage package, after execute the Appimage, it will create a `.desktop` file to associate protocol with coco:
```
ubuntu@ubuntu:~/.local/share/applications$ cat coco-handler.desktop 
[Desktop Entry]
Type=Application
Name=Coco-AI
Exec=/home/ubuntu/Documents/Coco-AI_0.1.0_aarch64.AppImage %u
Terminal=false
NoDisplay=true
MimeType=x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-scheme-handler/coco;x-s …
```
> fix: allow the to access deeplink for linux

- src-tauri/src/setup/mod.rs
the development environment automatically opens the console in the main window
> chore: the development environment automatically opens the console in the main window

- src-tauri/capabilities/default.json
fix macos double-click on main window crashes
> fix: fix macos double-click on main window crashes

- src-tauri/src/setup/mac.rs
macos main window changed to non-resizable
> refactor: macos main window changed to non-resizable

- src/routes/layout.tsx
disable right-click for production environment
> refactor: disable right-click for production environment

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/server/servers.rs
> chore: refresh all server's info on purpose, get the actual health info

- src-tauri/src/server/servers.rs
> fix: server should keep previous enabled state even on fresh

- docs/config.yaml
This pull request includes a change to the `docs/config.yaml` file to enhance the configuration for the book theme by specifying the output formats.
Configuration enhancements for book theme:
* [`docs/config.yaml`](diffhunk://#diff-06e23ea20a066a0e717b5eaa625dfd3f1d11439f4ad5bd705d16d6e1758b39c0R10-R15): Added `outputs` section to specify `HTML`, `RSS`, and `JSON` as output formats for the `home` page.
> chore: add settings to output docs json

- package.json
- src-tauri/Cargo.toml
> chore: lock `tauri-plugin-fs-pro` version to 2.3.1

- src-tauri/src/local/application.rs
Fix the issue that app search does not work on macOS
> fix: correct app default search path on macOS

- src-tauri/src/lib.rs
- src-tauri/src/util/mod.rs
- src/utils/tauriAdapter.ts
Fixes the app launching issue on Linux by implementing a custom `open()` command that invokes `gtk-launch` or `kde-open` under the hood to open apps from `.desktop` files.
> fix: app launching on Linux

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/server/http_client.rs
> fix: filter http query_args and convert only supported values

- src-tauri/src/local/application.rs
- src-tauri/src/search/mod.rs
1. Correct the `document.source.id` field in the returned documents.
2. In `query_coco_fusion()`, if the query string  `datasource` is present, use it to filter out the data sources that we should not search.
> fix: correct datasource ID in returned documents

- src-tauri/src/search/mod.rs
- src/commands/servers.ts
- src/components/Settings/Advanced/index.tsx
- src/hooks/useSyncStore.ts
- src/locales/en/translation.json
- src/locales/zh/translation.json
- src/pages/main/index.tsx
- src/stores/connectStore.ts
- src/types/platform.ts
Use the timeout value specified in the settings when invoking `query_coco_fusion()`.
> refactor: use timeout value specified in settings in query_coco_fusion()

- src/components/Settings/Advanced/index.tsx
- src/hooks/useSyncStore.ts
- src/stores/connectStore.ts
After this PR, we no longer use `queryTimeout` but `queryTimeoutRenamed` to store this configuration entry, requested by @medcl.
I tested locally
> refactor: rename the key used to store queryTimeout

- .github/workflows/release.yml
This pull request updates the release workflow to support an additional platform and improves dependency installation logic. The most important changes include adding support for the `ubuntu-22.04-arm` platform and refining the conditional logic and dependencies for Ubuntu-based builds.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R53-R54): Added support for the `ubuntu-22.04-arm` platform with the `aarch64-unknown-linux-gnu` target.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L70-R75): Updated the conditional logic for installing dependencies to use `startsWith(matrix.platform, 'ubuntu-22.04')` for better flexibility.
* …
> chore: add github action build arm64 platform

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
> chore: use ssh instead of https to pull pizza_engine

- package.json
- pnpm-lock.yaml
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/lib.rs
- src/routes/layout.tsx
Employ `tauri-plugin-log` as the logger. Here is what a log looks like:
```
[05-11 17:00:00] [INF] [coco_lib:625] Coco-AI started
```
With the current impl:
1. It logs to stdout and a log file, the path of the log file depends on the OS
| Platform | Value                                                                                    | Example                                           |
| -------- | ---------------------------------------------------------------------------------------- | ------------------------------------------------- |
| Linux    | `$XDG_DATA_HOME/{bundleIdentifier}/logs` or `$HOME/.local/share/{bundleIdentifier}/logs` | `/home/alice/.local/share/rs.coco.app/logs`     |
| macOS    | `{homeDir}/Library/Logs/{bundleIdentifier}` …
> refactor: set up tauri-plugin-log as the logger

- src-tauri/src/local/application/with_feature.rs
On Linux, the Coco app panicked with the following error:
```rust
memory allocation of xxx bytes failed
```
This line of code will https://github.com/infinilabs/pizza/blob/de36b19726d8bc4c4be21bdedcb5d24bdc6d7306/lib/engine/src/store/disk/mod.rs#L892 allocate `size * 2 * 8` bytes, and `size` was set too high, leading to an allocation failure. Decrease `size` to `100_000` to fix the issue.
Not quite sure why this didn't cause any issue on macOS, possibly because the allocator implementation difference between the 2 platforms.
> fix: panic caused memory allocation failure on Linux

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
Fix a bug where applications installed via Flatpak would be reported twice.
This PR does not contain any code changes, they are included in PR https://github.com/infinilabs/applications-rs/pull/6. See that PR description for the root cause of the bug and how it was resolved.
> fix: duplicate flatpak applications

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/local/application/with_feature.rs
Add `~/Applications` to the search path, for web apps installed from Chrome, they live under this directory.
> chore: add ~/Applications to search path on macOS

- src/components/ChatMessage/UserMessage.tsx
Before:
https://github.com/user-attachments/assets/8d3f754d-2918-4664-889b-9d8af49ad9ae
After:
https://github.com/user-attachments/assets/17196112-5f29-4cf9-9a75-ea300548560e
> refactor: optimize styling issues with chat content

- src/components/Settings/SettingsItem.tsx
> refactor: optimize the style problem of icons

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/ServerList.tsx
- src/components/Cloud/Cloud.tsx
- src/components/Cloud/Sidebar.tsx
> fix: server image loading failure

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/lib.rs
Allow us to configure dynamic log levels via the environment variable `COCO_LOG`. (If it is not set, use the current default log level, **INFO**.)
Generally, it mirrors the behavior of [`env_logger`](https://docs.rs/env_logger/latest/env_logger/#enabling-logging). Syntax: `COCO_LOG=<target>=<level>[,...]`, it is a log level triple sequence, separated by commas. Every log level triple consists of 3 parts:
1. target - which is the Rust crate or module name
2. = - an equal sign
3. level - the log level, which is case insensitive, "TRACE" is equivalent to "tRaCe"
target and level are optional:
* When the log level is omitted, e.g., `COCO_LOG=coco_lib`, the *TRACE* level will be used. 
* When the target is omitted, the specified log level will apply to all the targets, i.e., all the Rust …
> feat: dynamic log level via env var COCO_LOG

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/local/application/mod.rs
- src-tauri/src/local/application/with_feature.rs
- src/components/Settings/Extensions/components/Details/Application/index.tsx
- src/components/Settings/Extensions/index.tsx
Fix a panic that would happen when fetching app metadata on Windows. It also corrects application names, "chrome" -> "Google Chrome".
> fix: panic when fetching app metadata on Windows

- docs/content.en/docs/release-notes/_index.md
- src/components/Assistant/Chat.tsx
> fix: suggestion list position

- Makefile
Add a Makefile command that starts a dev server with feature `use_pizza_engine` enabled
> chore: add make cmd dev-build-with-pizza

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/server/servers.rs
> chore: mark unavailable server to offline on refresh info

- src-tauri/src/local/application/with_feature.rs
This thread causes memory leaks on macOS, still need to investigate the root cause and bring it back in the future. But for now, let's remove it for the near release.
> refactor: remove thread app list synchronizer as it leaks memory on macOS

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/extension/third_party.rs
- src-tauri/src/search/mod.rs
1. Make the ThirdPartyExtensions SearchSource implementation respect the `datasource` parameter if it is specified.
2. Refactor the error handling and logging code in `query_coco_fusion()` to make it clearer.
> fix: make extension search source respect parameter datasource

- .github/workflows/release.yml
This pull request updates the release workflow in `.github/workflows/release.yml` to include conditional steps for setting up and building the application with specific features based on the target platform. The most important changes are as follows:
* **Pizza engine setup for non-Windows i686 platforms**: Added a new step to set up pizza engine features (`make add-dep-pizza-engine`) before building the app. This step is conditionally executed for platforms other than `i686-pc-windows-msvc`.
* **Platform-specific build configurations**: Updated the build step to include platform-specific configurations and environment variables. For non-Windows i686 platforms, the build now includes the `--features use_pizza_engine` argument.
* **Separate build step for Windows i686**: Introduced a …
> chore: add pizza feature for release

- .github/workflows/release.yml
This pull request updates the `.github/workflows/release.yml` file to enhance the release workflow by adding steps for securely cloning a private repository on non-Windows platforms.
Enhancements to the release workflow:
* Added a step to set up an SSH agent for securely cloning private repositories, using the `webfactory/ssh-agent@v0.9.0` action and the `SSH_PRIVATE_KEY` secret. This step is skipped for Windows platforms.
* Added a step to add GitHub's server to the SSH known hosts file, ensuring secure SSH connections. This step is also skipped for Windows platforms.
> chore: add ssh private key for pizza engine

- .github/workflows/release.yml
- docs/content.en/docs/release-notes/_index.md
This pull request updates the `.github/workflows/release.yml` file to fix conditional checks for workflow steps, ensuring proper handling of the `matrix.target` and `matrix.platform` variables. The most important changes involve replacing outdated conditions to align with the intended logic.
* Replaced `matrix.platform` with `matrix.target` in conditional checks for steps like setting up the SSH agent, adding the Git server to known hosts, and configuring the pizza engine features setup. This ensures the conditions correctly reference the intended matrix variable.
* Updated the condition for the Windows i686-specific build step to use `matrix.target` instead of `matrix.platform`, maintaining consistency with the other changes.
> chore: fix ci publish error

- .github/workflows/release.yml
This pull request simplifies the GitHub Actions workflow for the release process by removing redundant steps and consolidating the build process. The most notable change is the removal of setup steps and build configurations that were previously applied to non-Windows targets.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L94-L136): Removed multiple steps related to SSH setup, adding Git server to known hosts, and configuring the "Pizza engine" for non-Windows targets. These steps are no longer necessary, which reduces complexity in the workflow.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L94-L136): Consolidated the build process by retaining …
> chore: rollback publish

- .github/workflows/release.yml
This pull request updates the `.github/workflows/release.yml` file to refine the setup process for building the app across different target platforms. The most important change is the conditional logic added to handle platform-specific dependencies.
* Updated the "Pizza engine features setup" step to include conditional logic for platform-specific dependency installation. For the `i686-pc-windows-msvc` target, it now adds the required Rust target using `rustup`. For other platforms, it runs `make add-dep-pizza-engine-linux` and adds the target using a nightly toolchain.
> fix: rustup for i688

- docs/content.en/docs/release-notes/_index.md
- src/hooks/useChatActions.ts
> fix: new chat assistant id not found

- src-tauri/src/extension/built_in/calculator.rs
- src-tauri/src/extension/third_party.rs
- src-tauri/src/search/mod.rs
Run:
* `<CalculatorSource as SearchSource>::search()`
* `<ThirdPartyExtensionsSearchSource as SearchSource>::search()`
in the blocking Tokio thread pool using `tokio::task::spawn_blocking()` because 
1. they are blocking, i.e., no `.await`
2. they could take more than 100 microseconds, which could affect the async runtime scheduling according to the suggestions from [this post](https://ryhl.io/blog/async-what-is-blocking/#:~:text=a%20good%20rule%20of%20thumb%20is%20no%20more%20than%2010%20to%20100%20microseconds%20between%20each%20.await.):
> To give a sense of scale of how much time is too much, a good rule of thumb is no more than 10 to 100 microseconds between each .await.
But querying the Coco cloud could still time out after this PR unless I set the timeout value to 800 milliseconds.
> refactor: execute Calculator/Extension search() in spawn_blocking

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/autostart.rs
- src-tauri/src/extension/built_in/pizza_engine_runtime.rs
- src-tauri/src/lib.rs
- src-tauri/src/setup/mac.rs
- src-tauri/src/shortcut.rs
* Add more logs for the `setup()` hook
* Refactor the `enable_autostart()` (renamed to `ensure_autostart_state_consistent()`) function to make its semantic more clear
> chore: more logs for the setup process

- docs/content.en/docs/release-notes/_index.md
- src/components/Search/MCPPopover.tsx
- src/components/Search/SearchPopover.tsx
> fix: input lost when reopening dialog after search

- src/commands/servers.ts
- src/components/Search/AssistantManager.tsx
- src/components/Search/AutoResizeTextarea.tsx
- src/components/Search/InputBox.tsx
- src/utils/tauriAdapter.ts
> refactor: blocking the default behavior of the tab key

- .github/workflows/release.yml
This pull request updates the `.github/workflows/release.yml` file to modify how dependencies are added for non-Windows targets during the release workflow.
* Replaced the `make add-dep-pizza-engine-linux` command with a direct `cargo add` command to add the `pizza-engine` dependency from a Git repository. This change also specifies additional features (`query_string_parser` and `persistence`) to be included when adding the dependency. (`[.github/workflows/release.ymlL112-R112](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L112-R112)`)
> fix: no make target with project

- docs/content.en/docs/release-notes/_index.md
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/extension/built_in/application/with_feature.rs
- src-tauri/src/extension/built_in/application/without_feature.rs
- src-tauri/src/extension/built_in/mod.rs
- src-tauri/src/extension/mod.rs
- src-tauri/src/extension/third_party.rs
- src/components/Settings/Extensions/components/Content/index.tsx
Before this PR, when an extension was disabled, its registered hotkey would still work, which should not happen since the extension is disabled. This PR fixes the issue.
Also, disabled extensions can no longer be modified and will appear grayed out in the settings page:
> fix: toggle extension should register/unregister hotkey

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/server/servers.rs
> fix: take coco server back on refresh

- src-tauri/src/extension/store.rs
1. Update category name "extension_store" -> "Extension Store"
2. Set an icon for the category
This PR does not need a release note.
> chore: update extension store category name and icon

- src-tauri/src/extension/store.rs
- src/components/Common/UI/Footer.tsx
- src/components/Search/AssistantManager.tsx
- src/components/Search/ContextMenu.tsx
- src/components/Search/ExtensionDetail.tsx
- src/utils/tauriAdapter.ts
> refactor: optimized some issues with extensions

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/extension/built_in/application/with_feature.rs
- src-tauri/src/extension/built_in/application/without_feature.rs
- src-tauri/src/lib.rs
Implements a tauri command that allows us to rebuild the applications index
> feat: interface `reindex_applications()`

- package.json
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
> chore: bump version number to 0.6.0

- .github/workflows/release.yml
chore: typo step name and remove too long env value
> chore: typo step name and env

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/extension/built_in/file_search.rs
- src-tauri/src/extension/mod.rs
1. In the `list_extensions(filter)` interface, if no filter is performed, don't do the extensions cleanup.
2. Change the extension type of "File Search" to "Extension"
> refactor: change File Search ext type to extension

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/extension/built_in/file_search.rs
Fix the issue that searching with the `SearchBy::NameAndContent` parameter will only search by file content
> fix(file search): searching by name&content does not search file name

- docs/content.en/docs/release-notes/_index.md
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
This commit replaces the meval-rs dependency with our [fork](https://github.com/infinilabs/meval-rs). The original meval-rs crate has not been maintained for a long time and uses nom 1.0, a crate that was released 9 years ago, which would be rejected by future Rust compiler because it contains outdated Rust syntaxes. This is the reason why we are seeing the following warning:
```
warning: the following packages contain code that will be rejected by a future version of Rust: nom v1.2.4
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1
```
Switching to our fork would solve this warning.
> chore: replace meval-rs with our fork to clear dep warning

- docs/content.en/docs/release-notes/_index.md
- src-tauri/Cargo.toml
- src-tauri/rust-toolchain.toml
- src-tauri/src/extension/mod.rs
- src-tauri/src/extension/third_party/mod.rs
- src-tauri/src/extension/third_party/store.rs
- src-tauri/src/lib.rs
- src/components/Search/ExtensionStore.tsx
In this commit, I refactored the extension code structure.
* We can only install third-party extensions so the `store.rs` file should belong to the `third_party` directory.
* Move tauri command `uninstall_extension()` to `extension/mod.rs` from `third_party.rs` since one can uninstall an extension regardless of how you installed it.
* Refactor the `install_extension_from_store()` function, add more descriptive code comments.
Also, a trivial change, bump Rust toolchain and edition to use the [let-chains](https://blog.rust-lang.org/2025/06/26/Rust-1.88.0/#let-chains) syntax.
> refactor: adjust extension code hierarchy

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
This commit bumps the windows crate from "0.60.0" to "0.61.3", it should solve the CI issue happened here[1]:
```text
error[E0277]: `DBOBJECT` doesn't implement `Debug`
--> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\windows-0.60.0\src\Windows\Win32\System\Search\mod.rs:21828:5
|
21826 | #[derive(Clone, Debug, PartialEq)]
|                 ----- in this derive macro expansion
21827 | pub struct SSVARIANT_0_4 {
21828 |     pub dbobj: DBOBJECT,
|     ^^^^^^^^^^^^^^^^^^^ the trait `Debug` is not implemented for `DBOBJECT`
|
= note: add `#[derive(Debug)]` to `DBOBJECT` or manually `impl Debug for DBOBJECT`
```
[1]: https://github.com/infinilabs/ci/actions/runs/16314479643/job/46076989290
> chore(deps): bump the windows crate

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/server/connector.rs
- src-tauri/src/server/datasource.rs
- src-tauri/src/server/http_client.rs
This commit adds a status code check to the following requests, only when this check passes, we deserialize the response JSON body:
- get_connectors_by_server
- mcp_server_search
- datasource_search
A helper function `status_code_check(response, allowed_status_codes)` is added to make refactoring easier.
> refactor: do status code check before deserializing response

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/extension/third_party/mod.rs
This commit fixes the bug that when an extension gets uninstalled, its registered hotkey won't be cleared.
> fix: unregister ext hotkey when it gets deleted

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/extension/built_in/application/with_feature.rs
This commit fixes the issue that indexing applications does not respect the search scope configuration, it always uses the default values.
> fix: indexing apps does not respect search scope config

- src/components/Settings/Extensions/index.tsx
> refactor: add border-radius to extended categories

- src/components/Cloud/ServiceAuth.tsx
- src/locales/en/translation.json
- src/locales/zh/translation.json
I’ve separated the links for the “User Agreement” and “Privacy Policy”, but the API still needs to provide the correct URLs.
> refactor: separate user agreement and privacy policy links

- src-tauri/src/lib.rs
- src/commands/servers.ts
Found this tauri command while reading the code, then I realized that
token management logic should all be kept in the backend, there is no
need to expose it to the frontend. And indeed, searching for it in the
frontend code showed that [it is not used at all](https://github.com/search?q=repo%3Ainfinilabs%2Fcoco-app+get_server_token+language%3ATypeScript&type=code&l=TypeScript).
```sh
$ cd src
$ rg get_server_token
commands/servers.ts
75:export function get_server_token(id: string): Promise<ServerTokenResponse> {
76:  return invokeWithErrorHandler(`get_server_token`, { id });
```
So remove it.
> chore: remove unused tauri cmd get_server_token

- src/commands/servers.ts
- src/types/commands.ts
After this commit[1], type `ServerTokenResponse` became unused, remove it as well.
[1]: https://github.com/infinilabs/coco-app/commit/57ab08fb6da66a7194164cccebd2a9b37ede401f
> chore: remove unused type ServerTokenResponse

- src-tauri/src/server/servers.rs
If a Coco server is available and enabled by the user, add it to the search source list if it hasn’t been added yet.
> fix: refreshing Coco server should register it to SearchSource

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/main.rs
Having backtrace in the panic log will help debugging a lot. Under release builds, we strip our binary so the symbols information is unavailable, but this information is still useful in debug builds.
Panic log in release builds:
```
Time: [YYYY-MM-DD-HH-MM-SS]
Location: [/Users/foo/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tauri-2.5.1/src/lib.rs:742:7]
Message: [state() called before manage() for tauri_plugin_global_shortcut::GlobalShortcut<tauri_runtime_wry::Wry<tauri::EventLoopMessage>>]
Backtrace:
0: __mh_execute_header
1: __mh_execute_header
2: __mh_execute_header
3: __mh_execute_header
4: __mh_execute_header
5: __mh_execute_header
6: __mh_execute_header
7: __mh_execute_header
8: __mh_execute_header
9: __mh_execute_header
10: __mh_execute_header
11: __mh_execute_header
12: …
```
> chore: display backtrace in panic log

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/lib.rs
This commit fixes the following panic:
```
Time: [2025-07-23-17-03-23]
Location: [/Users/steve/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tauri-2.5.1/src/lib.rs:742:7]
Message: [state() called before manage() for tauri_plugin_global_shortcut::GlobalShortcut<tauri_runtime_wry::Wry<tauri::EventLoopMessage>>]
```
The root cause is that, in a Tauri application, before you can access a piece of managed state with the .state() method, you must first register it with Tauri using .manage(). When a user reigsters hotkey for an extension, initializing extensions will invoke the .state() method, at that point, .manage() hasn't been called.
The fix is simple, we simply call .manage() earlies (invoked by our `shortcut::enable_shortcut(app)` function).
> fix: panic caused by "state() called before manage()"

- src-tauri/src/search/mod.rs
> chore: log querysources to search only when querysource is not set

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/lib.rs
- src-tauri/src/setup/mac.rs
- src/commands/system.ts
- src/components/Assistant/ChatHeader.tsx
- src/components/Common/UI/Footer.tsx
- src/hooks/useTogglePin.ts
This commit changes the default NS window attribute from `NSWindowCollectionBehaviorCanJoinAllSpaces` to `NSWindowCollectionBehaviorMoveToActiveSpace`. `NSWindowCollectionBehaviorCanJoinAllSpaces` has an issue on my macOS that the main window cannot be opened after running Coco for a while.
Pinning the main window would bring `NSWindowCollectionBehaviorCanJoinAllSpaces` back to make it really stay pinned across all the spaces. A tauri command `toggle_move_to_active_space_attribute()` is added to make this happen.
> chore: add toggle_move_to_active_space_attribute

- src-tauri/src/util/updater.rs
This commit adds a test for extract_build_number(), which I forgot to do in commit 067fb7144f6[1].
[1]: https://github.com/infinilabs/coco-app/commit/067fb7144f651f29d5d21d5e9c26f7be9b4ec1d7
> test: test extract_build_number()

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/assistant/mod.rs
- src-tauri/src/autostart.rs
- src-tauri/src/extension/built_in/application/with_feature.rs
- src-tauri/src/extension/built_in/application/without_feature.rs
- src-tauri/src/extension/built_in/file_search/config.rs
- src-tauri/src/extension/built_in/mod.rs
- src-tauri/src/extension/mod.rs
- src-tauri/src/extension/third_party/install/local_extension.rs
- src-tauri/src/extension/third_party/mod.rs
- src-tauri/src/lib.rs
- src-tauri/src/server/auth.rs
- src-tauri/src/server/connector.rs
- src-tauri/src/server/datasource.rs
- src-tauri/src/server/profile.rs
- src-tauri/src/server/servers.rs
- src-tauri/src/server/synthesize.rs
- src-tauri/src/settings.rs
- src-tauri/src/shortcut.rs
- src-tauri/src/util/mod.rs
This commit removes the generic argument R from all the AppHandle imports, which is feasible as it has a default type. This change is made not only for simplicity, but also **consistency**. Trait SearchSource uses this type:
```rust
pub trait SearchSource {
async fn search(
&self,
tauri_app_handle: AppHandle,
query: SearchQuery,
) -> Result<QueryResponse, SearchError>;
}
```
In order to make trait SearchSource object-safe, the AppHandle used in it cannot contain generic arguments. So some parts of Coco already omit this generic argument. This commit cleans up the remaining instances and unifies the usage project-wide.
> chore: ignore tauri::AppHandle's generic argument R

- src-tauri/src/lib.rs
- src-tauri/tauri.conf.json
Deep linking is handled on the frontend, so this commit removes the related and unused backend code.
"src-tauri/tauri.conf.json" is also modified, field "plugins.deep-link.schema" does not exist so I removed it as well.
> chore: remove unused deeplink-releated rust code

- docs/content.en/docs/release-notes/_index.md
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/extension/built_in/application/with_feature.rs
Bumps the 'applications' crate to include this commit[1].  With this, Coco now indexes iOS apps and macOS apps that store icons in Assets.car.
[1]: https://github.com/infinilabs/applications-rs/commit/814b16ea84fc0c5aa432fc094dfd9aceb83f7e46
> refactor: index iOS apps and macOS apps that store icon in Assets.car

- docs/content.en/docs/release-notes/_index.md
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/extension/built_in/application/with_feature.rs
- src-tauri/src/util/mod.rs
- src-tauri/src/util/system_lang.rs
After this commit, we index both English and Chinese application names so that searches in either language will work.  And the names of the applications in search results and application list will be in the app language.
Pizza index structure has been updated, but backward compatibility is preserved by keeping the support code for the old index field.
The changes in this commit are not macOS-specific, it applies to all supported platforms.  Though this feature won't work on Linux and Windows until we implement the localized app name support in the underlying applications-rs crate.
> feat: index both en/zh_CN app names and show app name in Coco app language

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/setup/mod.rs
Coco panicked on Windows when I was testing the applications-rs crate on Windows, the error message seemingly indicates that we should run hotkey setup on the main thread, and doing that indeed fixes the issue, so let's do it.
> fix: set up hotkey on main thread or Windows will complain

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
Bump it to include the support of localized app names for Linux.
> chore: bump applications-rs to latest commit

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/extension/built_in/file_search/implementation/macos.rs
This commit makes the file search conditions more permissive on macOS:
* Searching by filename
Now this is case-insensitive
* Searching by filename and content
We previously only searched for 2 attributes:
1. kMDItemFSName
2. kMDItemTextContent
as the semantics should be exactly right (Search fileanme and content).  But
kMDItemTextContent does not work as expected.  For example, if a PDF document
contains both "Waterloo" and "waterloo", it is only matched by "Waterloo".
To workaround this (I consider this a bug of Spotlight), now we search all
the attributes.
> refactor: relax the file search conditions on macOS

- .github/workflows/release.yml
- .github/workflows/rust_code_check.yml
- docs/content.en/docs/release-notes/_index.md
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/extension/built_in/file_search/implementation/linux_gnome.rs
- src-tauri/src/extension/built_in/file_search/implementation/macos.rs
- src-tauri/src/extension/built_in/file_search/implementation/mod.rs
- src-tauri/src/extension/built_in/file_search/implementation/windows.rs
- src-tauri/src/extension/built_in/file_search/mod.rs
- src-tauri/src/extension/built_in/mod.rs
- src-tauri/src/lib.rs
- src-tauri/src/util/file.rs
This commit implements the file search extension for Linux with the
GNOME desktop environment by employing the engine that powers GNOME's
desktop search - Tracker.
It also fixes an edge case bug that the search and exclude path
configuration entries will not work.  For example, say I set the search path
to ["~/Documents"], and I have a file named "Documents_foobarbuzz" under
my home directory, this file is not in the specified search path but
Coco would return it because we verified this by checking string prefix.
Claude Code found this when I asked it to write unit tests.  Thank both
tests and Claude Code.
> feat: file search for Linux/GNOME

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/extension/built_in/file_search/implementation/macos.rs
In the previous macOS file search implementation, we spawned an mdfind child process and killed it when we got the results we needed to avoid zombie processes.  However, this kill step would be skipped if an error happened during query results processing as we propagate errors.
This commit replaces the manual kill operation with the `ChildProcHandle.kill_on_drop()` API to let RAII do the job to fix the issue.
> fix: use kill_on_drop() to avoid zombie proc in error case

- src-tauri/src/util/system_lang.rs
The function `get_system_lang()` will only be used when the feature "use_pizza_engine" is enabled, feature-gate it to clear the compiler warning.
> chore: clean up unused warning

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/setup/mod.rs
- src/routes/layout.tsx
- src/types/platform.ts
This commit fixes(I guess?) the issue that the Settings window may not be
rendered or loaded, you will see that the whole window is gray in that case.
Background, aka, why this issue exists
=============================================================
In commit [1], we wrapped all the backend setup routines in a tauri command, so
that frontend code can call it before invoking any other backend interfaces to
guarantee that these interfaces won't be called until the data/state they rely
on is ready.
The implementation in [1] had an issue that it didn't work with window reloading.
To fix this issue, we made another commit [2].  Commit [2] fixed the refresh
issue, but it also caused the settings window issue that this commit tries to fix.
The backend setup tauri command needs a state to track …
> fix: settings window rendering/loading issue

- docs/content.en/docs/release-notes/_index.md
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
The previous versions of applications-rs would use CFBundleDisplayName or CFBundleName as the app name even though they were empty. Bump to the latest commit to fix the issue.
> fix: bump applications-rs to fix empty app name issue

- docs/content.en/docs/release-notes/_index.md
- src-tauri/src/extension/third_party/install/mod.rs
These 2 tags could contain local file paths, we need to `convertFileSrc()` them as well.
> chore: convertFileSrc() "link[href]" and "img[src]"

- src-tauri/src/extension/built_in/window_management/plugin.json
- src/hooks/useScript.ts
> refactor: update icons for window management extension

- src-tauri/src/extension/built_in/window_management/plugin.json
- src/hooks/useScript.ts
> refactor: update extension icon
